services:
  - type: web
    name: automacao-siged
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
      - key: HEADLESS
        value: "true"
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    autoDeploy: true